### ISSUE TITLE
Extra newline

### ISSUE THREAD

**Issue by LucidOne** [noahmorrison/chevron#30]
test.template
```
This is a {{test}}.
```

test.yml
```
---
test: "failed test"
```

```bash
$ chevron -d test.yml test.template 
This is a new test.

$
```

**Comment by LucidOne** [comment]
Problem seems to exist in both Python 2.7.13 and Python 3.5.3
Tested from pip and git

**Comment by noahmorrison** [comment]
Hey there,

Chevron handles newlines correctly (and is checked by unittests) allll the way up til the actual CLI method, because it takes the output string and `print`s it, which adds the extra newline.

I guess I never really use the CLI so I never noticed... Thanks for finding this!

Newest version (0.12.2) should behave like you expect (already posted to pypi).

**Comment by LucidOne** [comment]
Thanks for the quick response!
