### ISSUE TITLE
Drop Python 2.6, 3.2, and 3.3 from Travis CI

### ISSUE THREAD

**Issue by akosthekiss** [noahmorrison/chevron#42]
Diagnostics for the Python 2.6 job:

```
DEPRECATION: Python 2.6 is no longer supported by the Python core team
pycparser requires Python '>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*' but the running Python is 2.6.9
The command "pip install coveralls" failed and exited with 1
```

Diagnostics for the Python 3.2 and 3.3 jobs:

```
$ tox
File "/home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages/pkg_resources/__init__.py", line 90, in <module>
  raise RuntimeError("Python 3.4 or later is required")
RuntimeError: Python 3.4 or later is required
```

In the first case, coveralls cannot be installed anymore (because of a dependency), while in the last two cases, tox fails (because setuptools has dropped support for Python 3.3 since v40.0.0). It might be possible to get some of the job running with workarounds (e.g., by disabling coveralls for py2.6, or by downgrading setuptools for py3.2 and py3.3), but they are quite old variants unsupported by either the core Python team or by a quite core Python package, so they may not be worth the efforts.

I'd be willing to submit a PR to drop these if you'd agree.

**Comment by noahmorrison** [comment]
Not dropping support. Honestly I'd like to test on older versions of python (2.4, 2.5) as well if possible.

Chevron was made because [pystache](https://github.com/defunkt/pystache/pull/169) didn't support archaic versions of python. Chevron's goals in order are python compatibility, spec compatibility, speed. Obviously nobody should be choosing to use old versions of python in their new projects, but this library is for those who are forced to use old versions just as much as it is for those who have the ability to choose whatever language they want.

I will however fix the Travis CI (with your help, thanks for the PR's), because it being red is obviously bad (and was hiding flake8 errors I had merged in).

**Comment by akosthekiss** [comment]
Reasonable. Thank's for the feedback. Looking forward to a green CI badge. (And to a new pypi release perhaps?)

**Comment by noahmorrison** [comment]
How about [0.13.1](https://pypi.org/project/chevron/0.13.1/)?

**Comment by akosthekiss** [comment]
Perfect!
