### ISSUE TITLE
Python 3.8 -- YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated

### ISSUE THREAD

**Issue by Denubis** [noahmorrison/chevron#78]
```/home/ubuntu/.local/lib/python3.8/site-packages/chevron/main.py:23: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
```
Is a warning showing on run when I run this via python 3.8.1

**Comment by mardub1635** [comment]
Yes. same problem with python 3.7.
The problem is located in main.py, l.23:
            data = json.load(data_file)
One can solve it by replacing  l.23 by this line:
            data = json.safe_load(data_file)

Details: 
To understand this issue have a look at the import line 7 in main.py:
    import yaml as json
and have a look at this documentation:
https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation
